version: '3'

services:
  nginx:
    container_name: c-mess-nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8123:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    # restart: always